version: '3.8'

name: ragadoc

services:
  # Streamlit application
  ragadoc:
    build: .
    container_name: ragadoc-app
    ports:
      - "8501:8501"
    environment:
      # Configure Ollama connection (both env vars for compatibility)
      - OLLAMA_HOST=ollama:11434
      - OLLAMA_BASE_URL=http://ollama:11434
    restart: unless-stopped
    volumes:
      - ./data:/app/data  # For persistent data storage

  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_PORT=11434