name: ragnarok
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - setuptools
  - streamlit
  - pillow
  - pytest
  - pytest-cov
  - pypdf2
  - pdfplumber
  - pip:
    - ollama
    - streamlit-pdf-viewer
    - PyMuPDF
    - -e . 