name: ragadoc
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - setuptools
  - streamlit
  - pillow
  - pytest
  - pytest-cov
  - pypdf2
  - pdfplumber
  - pip:
    - ollama
    - streamlit-pdf-viewer
    - PyMuPDF
    - loguru
    - tiktoken
    - pymupdf4llm
    # RAG system dependencies
    - llama-index>=0.9.0
    - llama-index-embeddings-ollama>=0.1.0
    - llama-index-llms-ollama>=0.1.0
    - llama-index-vector-stores-chroma>=0.1.0
    - chromadb>=0.4.0
    - sentence-transformers>=2.2.0
    - -e . 